// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CloseDataChannel.proto

#ifndef PROTOBUF_CloseDataChannel_2eproto__INCLUDED
#define PROTOBUF_CloseDataChannel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace CloseDataChannel {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CloseDataChannel_2eproto();
void protobuf_AssignDesc_CloseDataChannel_2eproto();
void protobuf_ShutdownFile_CloseDataChannel_2eproto();

class CloseDataChannel;
class CloseDataChannelAck;

// ===================================================================

class CloseDataChannel : public ::google::protobuf::Message {
 public:
  CloseDataChannel();
  virtual ~CloseDataChannel();
  
  CloseDataChannel(const CloseDataChannel& from);
  
  inline CloseDataChannel& operator=(const CloseDataChannel& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CloseDataChannel& default_instance();
  
  void Swap(CloseDataChannel* other);
  
  // implements Message ----------------------------------------------
  
  CloseDataChannel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CloseDataChannel& from);
  void MergeFrom(const CloseDataChannel& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 signature = 1;
  inline bool has_signature() const;
  inline void clear_signature();
  static const int kSignatureFieldNumber = 1;
  inline ::google::protobuf::int64 signature() const;
  inline void set_signature(::google::protobuf::int64 value);
  
  // required bytes task_uuid = 2;
  inline bool has_task_uuid() const;
  inline void clear_task_uuid();
  static const int kTaskUuidFieldNumber = 2;
  inline const ::std::string& task_uuid() const;
  inline void set_task_uuid(const ::std::string& value);
  inline void set_task_uuid(const char* value);
  inline void set_task_uuid(const void* value, size_t size);
  inline ::std::string* mutable_task_uuid();
  
  // @@protoc_insertion_point(class_scope:CloseDataChannel.CloseDataChannel)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int64 signature_;
  ::std::string* task_uuid_;
  static const ::std::string _default_task_uuid_;
  friend void  protobuf_AddDesc_CloseDataChannel_2eproto();
  friend void protobuf_AssignDesc_CloseDataChannel_2eproto();
  friend void protobuf_ShutdownFile_CloseDataChannel_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CloseDataChannel* default_instance_;
};
// -------------------------------------------------------------------

class CloseDataChannelAck : public ::google::protobuf::Message {
 public:
  CloseDataChannelAck();
  virtual ~CloseDataChannelAck();
  
  CloseDataChannelAck(const CloseDataChannelAck& from);
  
  inline CloseDataChannelAck& operator=(const CloseDataChannelAck& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CloseDataChannelAck& default_instance();
  
  void Swap(CloseDataChannelAck* other);
  
  // implements Message ----------------------------------------------
  
  CloseDataChannelAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CloseDataChannelAck& from);
  void MergeFrom(const CloseDataChannelAck& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bytes task_uuid = 1;
  inline bool has_task_uuid() const;
  inline void clear_task_uuid();
  static const int kTaskUuidFieldNumber = 1;
  inline const ::std::string& task_uuid() const;
  inline void set_task_uuid(const ::std::string& value);
  inline void set_task_uuid(const char* value);
  inline void set_task_uuid(const void* value, size_t size);
  inline ::std::string* mutable_task_uuid();
  
  // required bool result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline bool result() const;
  inline void set_result(bool value);
  
  // optional int64 error_number = 3;
  inline bool has_error_number() const;
  inline void clear_error_number();
  static const int kErrorNumberFieldNumber = 3;
  inline ::google::protobuf::int64 error_number() const;
  inline void set_error_number(::google::protobuf::int64 value);
  
  // @@protoc_insertion_point(class_scope:CloseDataChannel.CloseDataChannelAck)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* task_uuid_;
  static const ::std::string _default_task_uuid_;
  bool result_;
  ::google::protobuf::int64 error_number_;
  friend void  protobuf_AddDesc_CloseDataChannel_2eproto();
  friend void protobuf_AssignDesc_CloseDataChannel_2eproto();
  friend void protobuf_ShutdownFile_CloseDataChannel_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CloseDataChannelAck* default_instance_;
};
// ===================================================================


// ===================================================================

// CloseDataChannel

// required int64 signature = 1;
inline bool CloseDataChannel::has_signature() const {
  return _has_bit(0);
}
inline void CloseDataChannel::clear_signature() {
  signature_ = GOOGLE_LONGLONG(0);
  _clear_bit(0);
}
inline ::google::protobuf::int64 CloseDataChannel::signature() const {
  return signature_;
}
inline void CloseDataChannel::set_signature(::google::protobuf::int64 value) {
  _set_bit(0);
  signature_ = value;
}

// required bytes task_uuid = 2;
inline bool CloseDataChannel::has_task_uuid() const {
  return _has_bit(1);
}
inline void CloseDataChannel::clear_task_uuid() {
  if (task_uuid_ != &_default_task_uuid_) {
    task_uuid_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& CloseDataChannel::task_uuid() const {
  return *task_uuid_;
}
inline void CloseDataChannel::set_task_uuid(const ::std::string& value) {
  _set_bit(1);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  task_uuid_->assign(value);
}
inline void CloseDataChannel::set_task_uuid(const char* value) {
  _set_bit(1);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  task_uuid_->assign(value);
}
inline void CloseDataChannel::set_task_uuid(const void* value, size_t size) {
  _set_bit(1);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  task_uuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CloseDataChannel::mutable_task_uuid() {
  _set_bit(1);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  return task_uuid_;
}

// -------------------------------------------------------------------

// CloseDataChannelAck

// required bytes task_uuid = 1;
inline bool CloseDataChannelAck::has_task_uuid() const {
  return _has_bit(0);
}
inline void CloseDataChannelAck::clear_task_uuid() {
  if (task_uuid_ != &_default_task_uuid_) {
    task_uuid_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& CloseDataChannelAck::task_uuid() const {
  return *task_uuid_;
}
inline void CloseDataChannelAck::set_task_uuid(const ::std::string& value) {
  _set_bit(0);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  task_uuid_->assign(value);
}
inline void CloseDataChannelAck::set_task_uuid(const char* value) {
  _set_bit(0);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  task_uuid_->assign(value);
}
inline void CloseDataChannelAck::set_task_uuid(const void* value, size_t size) {
  _set_bit(0);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  task_uuid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CloseDataChannelAck::mutable_task_uuid() {
  _set_bit(0);
  if (task_uuid_ == &_default_task_uuid_) {
    task_uuid_ = new ::std::string;
  }
  return task_uuid_;
}

// required bool result = 2;
inline bool CloseDataChannelAck::has_result() const {
  return _has_bit(1);
}
inline void CloseDataChannelAck::clear_result() {
  result_ = false;
  _clear_bit(1);
}
inline bool CloseDataChannelAck::result() const {
  return result_;
}
inline void CloseDataChannelAck::set_result(bool value) {
  _set_bit(1);
  result_ = value;
}

// optional int64 error_number = 3;
inline bool CloseDataChannelAck::has_error_number() const {
  return _has_bit(2);
}
inline void CloseDataChannelAck::clear_error_number() {
  error_number_ = GOOGLE_LONGLONG(0);
  _clear_bit(2);
}
inline ::google::protobuf::int64 CloseDataChannelAck::error_number() const {
  return error_number_;
}
inline void CloseDataChannelAck::set_error_number(::google::protobuf::int64 value) {
  _set_bit(2);
  error_number_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace CloseDataChannel

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CloseDataChannel_2eproto__INCLUDED
