// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "file_mount_stop_download.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace file_mount_stop_download {

namespace {


}  // namespace


void protobuf_AssignDesc_file_5fmount_5fstop_5fdownload_2eproto() {
  protobuf_AddDesc_file_5fmount_5fstop_5fdownload_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "file_mount_stop_download.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_file_5fmount_5fstop_5fdownload_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_file_5fmount_5fstop_5fdownload_2eproto() {
}

void protobuf_AddDesc_file_5fmount_5fstop_5fdownload_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::LogExportTask::protobuf_AddDesc_LogExportTask_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036file_mount_stop_download.proto\022\030file_m"
    "ount_stop_download\032\023LogExportTask.proto", 79);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "file_mount_stop_download.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_file_5fmount_5fstop_5fdownload_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_file_5fmount_5fstop_5fdownload_2eproto {
  StaticDescriptorInitializer_file_5fmount_5fstop_5fdownload_2eproto() {
    protobuf_AddDesc_file_5fmount_5fstop_5fdownload_2eproto();
  }
} static_descriptor_initializer_file_5fmount_5fstop_5fdownload_2eproto_;


// @@protoc_insertion_point(namespace_scope)

}  // namespace file_mount_stop_download

// @@protoc_insertion_point(global_scope)
